/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:98282591-7fc4-467e-b5ff-d53d96575852",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_76NClyJRO",
    "aws_user_pools_web_client_id": "37amq2fddktpej98km7ftdpmt0",
    "oauth": {},
    "aws_user_files_s3_bucket": "logo234510-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://w6sz5rtoifatzlpujtysdqkyj4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
